theme = "blowfish"
baseURL = "https://devdoit.github.io/"
defaultContentLanguage = "ko"
title = "DevDoit"

enableRobotsTXT = true
summaryLength = 30
hasCJKLanguage = true

buildDrafts = false
buildFuture = false

enableEmoji = true
timeZone = "Asia/Seoul"

[pagination]
  pagerSize = 10

[imaging]
  anchor = "Center"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10
