# -- 테마 옵션 --
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "auto" # light, dark, auto
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

disableImageOptimization = false

fingerprintAlgorithm = "sha512"

[header]
  layout = "basic" # basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # page, profile, hero, card, background, custom
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/diary/"
  cardView = true

[article]
  showDate = true
  showAuthor = false
  showHero = false
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showCategories = true
  showTags = true
  showWordCount = false
  showZenMode = false

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
